// mount & unmount events
export const MOUNT = 'MOUNT';
export const PAGE_VISIBLE = 'PAGE_VISIBLE';
export const PAGE_HIDDEN = 'PAGE_HIDDEN';

// click events
export const JOIN_CLICKED = 'JOIN_CLICKED';
export const QUESTIONS_TOGGLED = 'QUESTIONS_TOGGLED';
export const IM_GOOD_CLICKED = 'IM_GOOD_CLICKED';
export const EDIT_HEADLINE_CLICKED = 'EDIT_HEADLINE_CLICKED';
export const FEEDBACK_BTN_CLICKED = 'FEEDBACK_BTN_CLICKED';
export const FEEDBACK_SUBMITTED = 'FEEDBACK_SUBMITTED';
export const LINKEDIN_VIEWED = 'LINKEDIN_VIEWED';
export const PROFILE_PIC_VIEWED = 'PROFILE_PIC_VIEWED';
export const SORT_OPTION_CLICKED = 'SORT_OPTION_CLICKED';
export const CONTACT_US_CLICKED = 'CONTACT_US_CLICKED';
export const SIDENAV_MENU_CLICKED = 'SIDENAV_MENU_CLICKED';
export const SIGNIN_WITH_LINKEDIN_CLICKED = 'SIGNIN_WITH_LINKEDIN_CLICKED';
export const TERMS_OF_USE_CLICKED = 'TERMS_OF_USE_CLICKED';
