// CLIENT ONLY
export const CLEAR_STATE = "CLEAR_STATE";
export const SELECT_MESH = "SELECT_MESH";
export const POST_LOCATION_TO_STORE = "POST_LOCATION_TO_STORE";

// USER ROUTES //
export const FETCH_CURRENT_USER = "FETCH_CURRENT_USER";
export const EDIT_USER_INFO = "EDIT_USER_INFO";
export const ASSOCIATE_ORG_WITH_USER = "ASSOCIATE_ORG_WITH_USER";

// MESH ROUTES
export const CREATE_MESH = "CREATE_MESH";
export const FETCH_MESHES = "FETCH_MESHES";
export const FETCH_MESH_USERS = "FETCH_MESH_USERS";
export const ADD_MESH_USER = "ADD_MESH_USER";
export const EXIT_MESH_USER = "EXIT_MESH_USER";
export const ADD_MESH_FEEDBACK = "ADD_MESH_FEEDBACK";

// ORG ROUTES
export const CREATE_ORG = "CREATE_ORG";
export const FETCH_ORG = "FETCH_ORG";
export const FETCH_MEETUP_GROUP_INFO = "FETCH_MEETUP_GROUP_INFO";
export const SYNC_MEETUPS = "SYNC_MEETUPS";
export const FETCH_ORG_MESHES = "FETCH_ORG_MESHES";
export const SIGNIN_ORG = "SIGNIN_ORG";

// LOG ROUTES
export const CREATE_LOG = "CREATE_LOG";
